const ROUTES = {
    LOGIN: '/login',
    HOME: '/',
    SIGNUP: '/signup',
    FORGOT_PASSWORD: '/forgot-password',
    EMAIL_SENT: '/email-sent',
    COOKIE: '/cookie-settings',
    FAQ: '/faqs',
    PRICING: '/pricing',
    CONTACT_US: '/contact-us',
    BLOG: '/blog',
    API_DOCS: '/api-docs',
    SERVER_ERROR: '/error',
    PAGE_NOT_FOUND: '/page-not-found',
    PROFILE: '/profile',
    TEAM_ACCOUNT: '/team-account',
    COMPANY_GROUPS: '/team-account/company-groups',
    COMPANY_GROUP_DETAIL: '/team-account/company-groups/company-group-detail',
    PAYMENT_PLAN: '/payment-plan',
    PAYMENT: '/payment-plan/payment',
    STORAGES: '/storages',
    STORAGE_DETAIL: '/storages/storage-detail',
    TEMPLATES: '/templates',
    EMAILS: '/emails',
    EMAIL_BUILDER: '/email-builder',
    TEST: '/test',
};

export default ROUTES;
